import React from 'react';
import { DocNexusDocument } from '../types.js';
import { 
  X, 
  Download, 
  FileText, 
  Printer, 
  Code, 
  Table, 
  Archive,
  Check
} from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  document: DocNexusDocument;
  onAddLog: (log: any) => void;
  theme?: 'dark' | 'light';
}

export default function ExportModal({
  isOpen,
  onClose,
  document,
  onAddLog,
  theme = 'dark'
}: ExportModalProps) {
  if (!isOpen) return null;
  const isLight = theme === 'light';

  const downloadFile = (content: string, filename: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = window.document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);

    onAddLog({
      timestamp: new Date().toLocaleTimeString(),
      type: 'SUCCESS',
      message: `DOCNEXUS: Exported "${document.title}" as standalone ${filename} file.`
    });
    onClose();
  };

  const handleExportMarkdown = () => {
    const filename = `${document.title.toLowerCase().replace(/\s+/g, '_')}.md`;
    let fileContent = document.content;
    if (document.format !== 'markdown') {
      fileContent = `---
title: ${document.title}
format: ${document.format}
exportedAt: ${new Date().toISOString()}
---

\`\`\`json
${document.content}
\`\`\``;
    }
    downloadFile(fileContent, filename, 'text/markdown;charset=utf-8');
  };

  const handleExportHTML = () => {
    const filename = `${document.title.toLowerCase().replace(/\s+/g, '_')}.html`;
    const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${document.title} - SutharLabs Document</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 20px; color: #1e293b; background: #f8fafc; }
    h1 { font-size: 2.2rem; color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
    pre { background: #0f172a; color: #74f5ff; padding: 16px; border-radius: 8px; overflow-x: auto; font-family: monospace; }
    blockquote { border-left: 4px solid #00dbe7; margin: 0; padding-left: 16px; color: #475569; }
    footer { margin-top: 60px; font-size: 11px; color: #94a3b8; text-align: center; }
  </style>
</head>
<body>
  <h1>${document.title}</h1>
  <pre>${document.content}</pre>
  <footer>Generated by SutharLabs DocNexus Studio &copy; ${new Date().getFullYear()}</footer>
</body>
</html>`;
    downloadFile(htmlTemplate, filename, 'text/html;charset=utf-8');
  };

  const handleExportJSON = () => {
    const filename = `${document.title.toLowerCase().replace(/\s+/g, '_')}.nexus`;
    downloadFile(JSON.stringify(document, null, 2), filename, 'application/json;charset=utf-8');
  };

  const handleExportPrintPDF = () => {
    window.print();
    onAddLog({
      timestamp: new Date().toLocaleTimeString(),
      type: 'INFO',
      message: `DOCNEXUS: Triggered browser vector print layout for "${document.title}".`
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm select-none">
      <div className={`w-full max-w-lg rounded-2xl border shadow-2xl p-6 flex flex-col space-y-5 ${
        isLight ? 'bg-white border-slate-200 text-slate-800' : 'bg-[#0f0f13] border-outline/25 text-white'
      }`}>
        <div className={`flex items-center justify-between border-b pb-3 ${
          isLight ? 'border-slate-200' : 'border-outline/10'
        }`}>
          <div className="flex items-center gap-2">
            <Download className={`w-5 h-5 ${isLight ? 'text-indigo-600' : 'text-[#00dbe7]'}`} />
            <h3 className={`font-bold text-base font-sans ${isLight ? 'text-slate-900' : 'text-white'}`}>Export Sovereign Artifact</h3>
          </div>
          <button
            onClick={onClose}
            className={`p-1 rounded ${
              isLight ? 'hover:bg-slate-100 text-slate-500 hover:text-slate-800' : 'hover:bg-white/10 text-on-surface-variant hover:text-white'
            }`}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <p className={`text-xs leading-relaxed ${isLight ? 'text-slate-600' : 'text-on-surface-variant'}`}>
          Select target file format to compile and download <strong className={isLight ? 'text-slate-900' : 'text-white'}>"{document.title}"</strong>:
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 font-mono text-xs">
          <button
            onClick={handleExportPrintPDF}
            className={`p-3.5 rounded-xl border flex items-center gap-3 text-left transition-all cursor-pointer ${
              isLight
                ? 'border-slate-200 hover:border-purple-500 bg-slate-50 hover:bg-purple-50/60'
                : 'border-outline/20 hover:border-[#ce5dff] bg-surface-container-low/40 hover:bg-[#ce5dff]/10'
            }`}
          >
            <Printer className="w-5 h-5 text-[#ce5dff] shrink-0" />
            <div>
              <span className={`font-bold block ${isLight ? 'text-slate-900' : 'text-white'}`}>Print / PDF</span>
              <span className={`text-[10px] ${isLight ? 'text-slate-500' : 'text-on-surface-variant'}`}>Vector paginated layout</span>
            </div>
          </button>

          <button
            onClick={handleExportMarkdown}
            className={`p-3.5 rounded-xl border flex items-center gap-3 text-left transition-all cursor-pointer ${
              isLight
                ? 'border-slate-200 hover:border-indigo-500 bg-slate-50 hover:bg-indigo-50/60'
                : 'border-outline/20 hover:border-[#00dbe7] bg-surface-container-low/40 hover:bg-[#00dbe7]/10'
            }`}
          >
            <FileText className={`w-5 h-5 shrink-0 ${isLight ? 'text-indigo-600' : 'text-[#00dbe7]'}`} />
            <div>
              <span className={`font-bold block ${isLight ? 'text-slate-900' : 'text-white'}`}>Markdown (.md)</span>
              <span className={`text-[10px] ${isLight ? 'text-slate-500' : 'text-on-surface-variant'}`}>Clean raw Markdown file</span>
            </div>
          </button>

          <button
            onClick={handleExportHTML}
            className={`p-3.5 rounded-xl border flex items-center gap-3 text-left transition-all cursor-pointer ${
              isLight
                ? 'border-slate-200 hover:border-emerald-500 bg-slate-50 hover:bg-emerald-50'
                : 'border-outline/20 hover:border-[#00e476] bg-surface-container-low/40 hover:bg-[#00e476]/10'
            }`}
          >
            <Code className="w-5 h-5 text-[#00e476] shrink-0" />
            <div>
              <span className={`font-bold block ${isLight ? 'text-slate-900' : 'text-white'}`}>Styled HTML (.html)</span>
              <span className={`text-[10px] ${isLight ? 'text-slate-500' : 'text-on-surface-variant'}`}>Standalone web page</span>
            </div>
          </button>

          <button
            onClick={handleExportJSON}
            className={`p-3.5 rounded-xl border flex items-center gap-3 text-left transition-all cursor-pointer ${
              isLight
                ? 'border-slate-200 hover:border-amber-500 bg-slate-50 hover:bg-amber-50'
                : 'border-outline/20 hover:border-[#ffd700] bg-surface-container-low/40 hover:bg-[#ffd700]/10'
            }`}
          >
            <Archive className="w-5 h-5 text-amber-500 shrink-0" />
            <div>
              <span className={`font-bold block ${isLight ? 'text-slate-900' : 'text-white'}`}>Nexus JSON (.nexus)</span>
              <span className={`text-[10px] ${isLight ? 'text-slate-500' : 'text-on-surface-variant'}`}>Lossless project backup</span>
            </div>
          </button>
        </div>
      </div>
    </div>
  );
}
